// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOem8GSuITfTr2Y70C9mbaozJMzi4a84k',
    appId: '1:348772262119:web:9fd5fcfe8b1944ecee4242',
    messagingSenderId: '348772262119',
    projectId: 'admin-side-e7d3f',
    authDomain: 'admin-side-e7d3f.firebaseapp.com',
    storageBucket: 'admin-side-e7d3f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXrNMaTQWU-AiWwDeXfcmSvq9IJDzaUI8',
    appId: '1:348772262119:android:e5db868251a400fcee4242',
    messagingSenderId: '348772262119',
    projectId: 'admin-side-e7d3f',
    storageBucket: 'admin-side-e7d3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHX60F2I6Dg6WRNNTFHQLaEhas60QUU5Y',
    appId: '1:348772262119:ios:c6f76cf826b47648ee4242',
    messagingSenderId: '348772262119',
    projectId: 'admin-side-e7d3f',
    storageBucket: 'admin-side-e7d3f.appspot.com',
    iosClientId: '348772262119-1utp0rb1cmqq7ctp0ilapkp6hv352c7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminSide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHX60F2I6Dg6WRNNTFHQLaEhas60QUU5Y',
    appId: '1:348772262119:ios:936b0e8428bfa7bcee4242',
    messagingSenderId: '348772262119',
    projectId: 'admin-side-e7d3f',
    storageBucket: 'admin-side-e7d3f.appspot.com',
    iosClientId: '348772262119-g97un12kqf6ci19i0048g1hkck5anomt.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminSide.RunnerTests',
  );
}
